// B2B and professional service categories most likely to buy AI consulting/automation
export const PROSPECT_CATEGORIES = [
  'Law firms',
  'Accounting firms',
  'Real estate agencies',
  'Marketing agencies',
  'Financial advisors',
  'Insurance agencies',
  'Staffing agencies',
  'IT services companies',
  'Property management companies',
  'Mortgage brokers',
  'Business consulting firms',
  'HR consulting firms',
  'Logistics companies',
  'Healthcare clinics',
  'Dental offices',
  'Veterinary clinics',
  'Physical therapy clinics',
  'Commercial construction companies',
  'Engineering firms',
  'Architecture firms',
]

export const US_CITIES = [
  'New York, NY', 'Los Angeles, CA', 'Chicago, IL', 'Houston, TX', 'Phoenix, AZ',
  'Philadelphia, PA', 'San Antonio, TX', 'San Diego, CA', 'Dallas, TX', 'San Jose, CA',
  'Austin, TX', 'Jacksonville, FL', 'Fort Worth, TX', 'Columbus, OH', 'Charlotte, NC',
  'San Francisco, CA', 'Indianapolis, IN', 'Seattle, WA', 'Denver, CO', 'Nashville, TN',
  'Oklahoma City, OK', 'El Paso, TX', 'Washington, DC', 'Las Vegas, NV', 'Louisville, KY',
  'Memphis, TN', 'Portland, OR', 'Baltimore, MD', 'Milwaukee, WI', 'Albuquerque, NM',
  'Tucson, AZ', 'Fresno, CA', 'Mesa, AZ', 'Sacramento, CA', 'Atlanta, GA',
  'Kansas City, MO', 'Omaha, NE', 'Colorado Springs, CO', 'Raleigh, NC', 'Miami, FL',
  'Long Beach, CA', 'Virginia Beach, VA', 'Minneapolis, MN', 'Tampa, FL', 'New Orleans, LA',
  'Arlington, TX', 'Bakersfield, CA', 'Anaheim, CA', 'Aurora, CO', 'Corpus Christi, TX',
  'Riverside, CA', 'Lexington, KY', 'St. Louis, MO', 'Pittsburgh, PA', 'Stockton, CA',
  'Cincinnati, OH', 'St. Paul, MN', 'Toledo, OH', 'Greensboro, NC', 'Newark, NJ',
  'Plano, TX', 'Henderson, NV', 'Orlando, FL', 'Chandler, AZ', 'St. Petersburg, FL',
  'Norfolk, VA', 'Madison, WI', 'Durham, NC', 'Lubbock, TX', 'Winston-Salem, NC',
  'Garland, TX', 'Glendale, AZ', 'Hialeah, FL', 'Reno, NV', 'Baton Rouge, LA',
  'Irvine, CA', 'Chesapeake, VA', 'Irving, TX', 'Scottsdale, AZ', 'Fremont, CA',
  'Gilbert, AZ', 'San Bernardino, CA', 'Birmingham, AL', 'Rochester, NY', 'Richmond, VA',
  'Spokane, WA', 'Des Moines, IA', 'Montgomery, AL', 'Tacoma, WA', 'Akron, OH',
  'Providence, RI', 'Salt Lake City, UT', 'Knoxville, TN', 'Fort Lauderdale, FL',
  'Shreveport, LA', 'Augusta, GA', 'Huntsville, AL', 'Grand Rapids, MI', 'Tallahassee, FL',
  'Overland Park, KS', 'Glendale, CA', 'Columbus, GA', 'Cape Coral, FL', 'Little Rock, AR',
]
